id: stoiximan
siteId: 4
active: true
baseUrl: https://en.stoiximan.gr
parser: parsers.Stoiximan
tournaments:
  - sport/podosfairo/agglia/premier-league/1/
  - sport/podosfairo/germania/bundesliga/216/
  - sport/podosfairo/italia/serie-a/1635/
  - sport/podosfairo/ispania/laliga/5/
  - sport/podosfairo/agglia/championship/2r/
  - sport/podosfairo/ellada/super-league-1/1636r/
  - sport/podosfairo/gallia/ligue-1/215r/
  - sport/podosfairo/ollandia/eredivisie/17067r/
urls:
  live: live/
  day: sport/podosfairo/kouponi-agones-simera/