id: netbet
siteId: 8
active: false
baseUrl: https://ws-sport.netbet.gr/component/data
parser: parsers.Netbet
urls:
  home:
  live:
  day:
  highlights:
tournaments:
  - /ποδόσφαιρο/ελλάδα/σούπερ-λίγκα/
  - /ποδόσφαιρο/ιταλία/1η-κατηγορία/
  - /ποδόσφαιρο/ισπανία/1η-κατηγορία/
  - /ποδόσφαιρο/γερμανία/μπουντεσλίγκα/
  - /ποδόσφαιρο/αγγλία/πρέμιερ-λιγκ/
  - /ποδόσφαιρο/αγγλία/τσάμπιονσιπ/
  - /ποδόσφαιρο/γαλλία/ligue-1/
  - /ποδόσφαιρο/ολλανδία/ερεντιβίζιε/