id: novibet
siteId: 2
active: true
baseUrl: https://www.novibet.gr/
parser: parsers.Novibet
urls:
  home: api/marketviews?lang=en-US&oddsR=1&timeZ=GTB%20Standard%20Time&usrGrp=GR&timestamp=
  live: api/marketviews/location/16/4390?lang=en-US&oddsR=1&timeZ=GTB%20Standard%20Time&usrGrp=GR&timestamp=
  day: api/marketviews/location/16/912152?lang=en-US&oddsR=1&timeZ=GTB%20Standard%20Time&usrGrp=GR&timestamp=
  highlights: api/marketviews/location/16/55382?lang=en-US&oddsR=1&timeZ=GTB%20Standard%20Time&usrGrp=GR&timestamp=
tournaments:
  - api/marketviews/coupon/16/440817/3381277?lang=en-US&oddsR=1&timeZ=GTB%20Standard%20Time&usrGrp=GR&_= # superligue
  - api/marketviews/coupon/16/440817/4072230?lang=en-US&oddsR=1&timeZ=GTB%20Standard%20Time&usrGrp=GR&_= # serie 1
  - api/marketviews/coupon/16/440817/4087867?lang=en-US&oddsR=1&timeZ=GTB%20Standard%20Time&usrGrp=GR&_= # La liga
  - api/marketviews/coupon/16/440817/4091375?lang=en-US&oddsR=1&timeZ=GTB%20Standard%20Time&usrGrp=GR&_= # bundesliga
  - api/marketviews/coupon/16/440817/4069479?lang=en-US&oddsR=1&timeZ=GTB%20Standard%20Time&usrGrp=GR&_= # premier league
  - api/marketviews/coupon/16/440817/4069524?lang=en-US&oddsR=1&timeZ=GTB%20Standard%20Time&usrGrp=GR&_= # championship
  - api/marketviews/coupon/16/440817/4069626?lang=en-US&oddsR=1&timeZ=GTB%20Standard%20Time&usrGrp=GR&_= # ligue 1
  - api/marketviews/coupon/16/440817/4095187?lang=en-US&oddsR=1&timeZ=GTB%20Standard%20Time&usrGrp=GR&_= # eredivisie
